array1 = [
  {
    address: {
      geolocation: { lat: "-37.3159", long: "81.1496" },
      city: "kilcoole",
      street: "new road",
      number: 7682,
      zipcode: "12926-3874",
    },
    id: 1,
    email: "john@gmail.com",
    username: "johnd",
    password: "m38rmF$",
    name: { firstname: "john", lastname: "doe" },
    phone: "1-570-236-7033",
    __v: 0,
  },
  {
    address: {
      geolocation: { lat: "-37.3159", long: "81.1496" },
      city: "kilcoole",
      street: "Lovers Ln",
      number: 7267,
      zipcode: "12926-3874",
    },
    id: 2,
    email: "morrison@gmail.com",
    username: "mor_2314",
    password: "83r5^_",
    name: { firstname: "david", lastname: "morrison" },
    phone: "1-570-236-7033",
    __v: 0,
  },
  {
    address: {
      geolocation: { lat: "40.3467", long: "-30.1310" },
      city: "Cullman",
      street: "Frances Ct",
      number: 86,
      zipcode: "29567-1452",
    },
    id: 3,
    email: "kevin@gmail.com",
    username: "kevinryan",
    password: "kev02937@",
    name: { firstname: "kevin", lastname: "ryan" },
    phone: "1-567-094-1345",
    __v: 0,
  },
  {
    address: {
      geolocation: { lat: "50.3467", long: "-20.1310" },
      city: "San Antonio",
      street: "Hunters Creek Dr",
      number: 6454,
      zipcode: "98234-1734",
    },
    id: 4,
    email: "don@gmail.com",
    username: "donero",
    password: "ewedon",
    name: { firstname: "don", lastname: "romer" },
    phone: "1-765-789-6734",
    __v: 0,
  },
  {
    address: {
      geolocation: { lat: "40.3467", long: "-40.1310" },
      city: "san Antonio",
      street: "adams St",
      number: 245,
      zipcode: "80796-1234",
    },
    id: 5,
    email: "derek@gmail.com",
    username: "derek",
    password: "jklg*_56",
    name: { firstname: "derek", lastname: "powell" },
    phone: "1-956-001-1945",
    __v: 0,
  },
  {
    address: {
      geolocation: { lat: "20.1677", long: "-10.6789" },
      city: "el paso",
      street: "prospect st",
      number: 124,
      zipcode: "12346-0456",
    },
    id: 6,
    email: "david_r@gmail.com",
    username: "david_r",
    password: "3478*#54",
    name: { firstname: "david", lastname: "russell" },
    phone: "1-678-345-9856",
    __v: 0,
  },
  {
    address: {
      geolocation: { lat: "10.3456", long: "20.6419" },
      city: "fresno",
      street: "saddle st",
      number: 1342,
      zipcode: "96378-0245",
    },
    id: 7,
    email: "miriam@gmail.com",
    username: "snyder",
    password: "f238&@*$",
    name: { firstname: "miriam", lastname: "snyder" },
    phone: "1-123-943-0563",
    __v: 0,
  },
  {
    address: {
      geolocation: { lat: "50.3456", long: "10.6419" },
      city: "mesa",
      street: "vally view ln",
      number: 1342,
      zipcode: "96378-0245",
    },
    id: 8,
    email: "william@gmail.com",
    username: "hopkins",
    password: "William56$hj",
    name: { firstname: "william", lastname: "hopkins" },
    phone: "1-478-001-0890",
    __v: 0,
  },
  {
    address: {
      geolocation: { lat: "40.12456", long: "20.5419" },
      city: "miami",
      street: "avondale ave",
      number: 345,
      zipcode: "96378-0245",
    },
    id: 9,
    email: "kate@gmail.com",
    username: "kate_h",
    password: "kfejk@*_",
    name: { firstname: "kate", lastname: "hale" },
    phone: "1-678-456-1934",
    __v: 0,
  },
  {
    address: {
      geolocation: { lat: "30.24788", long: "-20.545419" },
      city: "fort wayne",
      street: "oak lawn ave",
      number: 526,
      zipcode: "10256-4532",
    },
    id: 10,
    email: "jimmie@gmail.com",
    username: "jimmie_k",
    password: "klein*#%*",
    name: { firstname: "jimmie", lastname: "klein" },
    phone: "1-104-001-4567",
    __v: 0,
  },
];
array2 = [
  {
    id: "rec43w3ipXvP28vog",
    fields: {
      company: "ikea",
      colors: ["#f15025", "#222"],
      featured: true,
      price: 999,
      name: "high-back bench",
      image: [
        {
          id: "attcvDDMikF6G2iNi",
          width: 1000,
          height: 639,
          url: "https://course-api.com/images/store/product-1.jpeg",
          filename: "product-1.jpeg",
          size: 62864,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: "https://course-api.com/images/store/product-1.jpeg",
              width: 56,
              height: 36,
            },
            large: {
              url: "https://course-api.com/images/store/product-1.jpeg",
              width: 801,
              height: 512,
            },
            full: {
              url: "https://course-api.com/images/store/product-1.jpeg",
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
    },
  },
  {
    id: "rec4f2RIftFCb7aHh",
    fields: {
      company: "marcos",
      colors: ["#f15025", "#222"],
      price: 7999,
      name: "albany table",
      image: [
        {
          id: "attP2cUyxU35M1zbw",
          width: 1000,
          height: 1500,
          url: "https://course-api.com/images/store/product-2.jpeg",
          filename: "product-1.jpeg",
          size: 119274,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: "https://course-api.com/images/store/product-2.jpeg",
              width: 24,
              height: 36,
            },
            large: {
              url: "https://course-api.com/images/store/product-2.jpeg",
              width: 512,
              height: 768,
            },
            full: {
              url: "https://course-api.com/images/store/product-2.jpeg",
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
    },
  },
  {
    id: "rec8kkCmSiMkbkiko",
    fields: {
      company: "caressa",
      colors: ["#222", "#0000ff", "#f15025"],
      price: 2599,
      name: "accent chair",
      image: [
        {
          id: "attIieysyB9zQmQo9",
          width: 1000,
          height: 667,
          url: "https://course-api.com/images/store/product-3.jpeg",
          filename: "product-4.jpeg",
          size: 49641,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: "https://course-api.com/images/store/product-3.jpeg",
              width: 54,
              height: 36,
            },
            large: {
              url: "https://course-api.com/images/store/product-3.jpeg",
              width: 768,
              height: 512,
            },
            full: {
              url: "https://course-api.com/images/store/product-3.jpeg",
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
    },
  },
  {
    id: "recBohCqQsot4Q4II",
    fields: {
      company: "caressa",
      colors: ["#ff0000", "#0000ff"],
      price: 4599,
      name: "wooden table",
      image: [
        {
          id: "attXaEED3KJcY2cjY",
          width: 1280,
          height: 1891,
          url: "https://course-api.com/images/store/product-4.jpeg",
          filename: "pexels-dominika-roseclay-1139785.jpg",
          size: 203105,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: "https://course-api.com/images/store/product-4.jpeg",
              width: 24,
              height: 36,
            },
            large: {
              url: "https://course-api.com/images/store/product-4.jpeg",
              width: 512,
              height: 756,
            },
            full: {
              url: "https://course-api.com/images/store/product-4.jpeg",
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
    },
  },
  {
    id: "recDG1JRZnbpRHpoy",
    fields: {
      company: "caressa",
      colors: ["#ff0000", "#f15025"],
      price: 699,
      name: "dining table",
      image: [
        {
          id: "attxkKEEgmBnutpwI",
          width: 1280,
          height: 1858,
          url: "https://course-api.com/images/store/product-5.jpeg",
          filename: "product-8.jpg",
          size: 281908,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: "https://course-api.com/images/store/product-5.jpeg",
              width: 25,
              height: 36,
            },
            large: {
              url: "https://course-api.com/images/store/product-5.jpeg",
              width: 512,
              height: 743,
            },
            full: {
              url: "https://course-api.com/images/store/product-5.jpeg",
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
    },
  },
  {
    id: "recNWGyP7kjFhSqw3",
    fields: {
      company: "liddy",
      colors: ["#0000ff"],
      price: 6999,
      name: "sofa set",
      image: [
        {
          id: "att5iyl4TJvd3oepN",
          width: 1000,
          height: 625,
          url: "https://course-api.com/images/store/product-6.jpeg",
          filename: "product-1.jpeg",
          size: 56151,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: "https://course-api.com/images/store/product-6.jpeg",
              width: 58,
              height: 36,
            },
            large: {
              url: "https://course-api.com/images/store/product-6.jpeg",
              width: 819,
              height: 512,
            },
            full: {
              url: "https://course-api.com/images/store/product-6.jpeg",
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
    },
  },
  {
    id: "recZEougL5bbY4AEx",
    fields: {
      company: "marcos",
      colors: ["#00ff00", "#f15025", "#ff0000"],
      price: 899,
      name: "modern bookshelf",
      image: [
        {
          id: "attDj1C6GxJMsJ1he",
          width: 1280,
          height: 720,
          url: "https://course-api.com/images/store/product-7.jpeg",
          filename: "product-7.jpg",
          size: 162415,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: "https://course-api.com/images/store/product-7.jpeg",
              width: 64,
              height: 36,
            },
            large: {
              url: "https://course-api.com/images/store/product-7.jpeg",
              width: 910,
              height: 512,
            },
            full: {
              url: "https://course-api.com/images/store/product-7.jpeg",
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
    },
  },
  {
    id: "recjMK1jgTb2ld7sv",
    fields: {
      company: "liddy",
      colors: ["#f15025"],
      price: 2199,
      name: "emperor bed",
      image: [
        {
          id: "attiwrd7gSI1oGxRK",
          width: 1280,
          height: 720,
          url: "https://course-api.com/images/store/product-8.jpeg",
          filename: "product-6.jpg",
          size: 178908,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: "https://course-api.com/images/store/product-8.jpeg",
              width: 64,
              height: 36,
            },
            large: {
              url: "https://course-api.com/images/store/product-8.jpeg",
              width: 910,
              height: 512,
            },
            full: {
              url: "https://course-api.com/images/store/product-8.jpeg",
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
    },
  },
  {
    id: "recmg2a1ctaEJNZhu",
    fields: {
      company: "marcos",
      colors: ["#00ff00", "#0000ff"],
      featured: true,
      price: 3995,
      name: "utopia sofa",
      image: [
        {
          id: "attqutUt355traBeS",
          width: 1280,
          height: 846,
          url: "https://course-api.com/images/store/product-9.jpeg",
          filename: "product-3.jpg",
          size: 196312,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: "https://course-api.com/images/store/product-9.jpeg",
              width: 54,
              height: 36,
            },
            large: {
              url: "https://course-api.com/images/store/product-9.jpeg",
              width: 775,
              height: 512,
            },
            full: {
              url: "https://course-api.com/images/store/product-9.jpeg",
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
    },
  },
  {
    id: "recvKMNR3YFw0bEt3",
    fields: {
      company: "liddy",
      colors: ["#ff0000", "#00ff00"],
      featured: true,
      price: 2998,
      name: "entertainment center",
      image: [
        {
          id: "atttOzyYI8P1XfJu8",
          width: 1280,
          height: 924,
          url: "https://course-api.com/images/store/product-10.jpeg",
          filename: "product-2.jpg",
          size: 195175,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: "https://course-api.com/images/store/product-10.jpeg",
              width: 50,
              height: 36,
            },
            large: {
              url: "https://course-api.com/images/store/product-10.jpeg",
              width: 709,
              height: 512,
            },
            full: {
              url: "https://course-api.com/images/store/product-10.jpeg",
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
    },
  },
  {
    id: "recxaXFy5IW539sgM",
    fields: {
      company: "ikea",
      colors: ["#00ff00", "#ff0000"],
      price: 1099,
      name: "albany sectional",
      image: [
        {
          id: "attjWNxk7KKzcLPDx",
          width: 1000,
          height: 652,
          url: "https://course-api.com/images/store/product-11.jpeg",
          filename: "product-1.jpeg",
          size: 61946,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: "https://course-api.com/images/store/product-11.jpeg",
              width: 55,
              height: 36,
            },
            large: {
              url: "https://course-api.com/images/store/product-11.jpeg",
              width: 785,
              height: 512,
            },
            full: {
              url: "https://course-api.com/images/store/product-11.jpeg",
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
    },
  },
  {
    id: "recyqtRglGNGtO4Q5",
    fields: {
      company: "liddy",
      colors: ["#222"],
      price: 999,
      name: "leather sofa",
      image: [
        {
          id: "attnZHyyOUTBzJ1ZD",
          width: 1280,
          height: 960,
          url: "https://course-api.com/images/store/product-12.jpeg",
          filename: "product-5.jpg",
          size: 189559,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: "https://course-api.com/images/store/product-12.jpeg",
              width: 48,
              height: 36,
            },
            large: {
              url: "https://course-api.com/images/store/product-12.jpeg",
              width: 683,
              height: 512,
            },
            full: {
              url: "https://course-api.com/images/store/product-12.jpeg",
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
    },
  },
];
